/**
 * Coach AI Profile Context
 *
 * Central utility that reads the approved AI profile of a coach and returns
 * a formatted text block ready to be injected into any AI prompt.
 *
 * Usage in any AI route:
 *   const coachContext = await getCoachAIProfileContext(coachId)
 *   const fullPrompt = coachContext + '\n\n' + taskSpecificPrompt
 *
 * If no approved profile exists, returns a neutral fallback that doesn't
 * break functionality — the AI simply operates without personalization.
 */

import { getCoachAIProfile } from '@/data/coach-ai-profile'

/**
 * Build the coach context block for an AI prompt.
 *
 * @param coachId - The coach's ID. Pass null/undefined to skip (returns fallback).
 * @returns A formatted string block ready to prepend to any AI prompt.
 */
export async function getCoachAIProfileContext(
    coachId: string | null | undefined
): Promise<string> {
    if (!coachId) return FALLBACK_CONTEXT

    const profile = await getCoachAIProfile(coachId)

    // No profile, or not yet approved → use neutral fallback
    if (!profile || profile.profile_status !== 'approved') return FALLBACK_CONTEXT

    // Build the context block from the approved profile
    const parts: string[] = [
        '## Perfil y metodología del coach',
        '',
    ]

    // System prompt (the richest source — generated by Gemini from the full onboarding)
    if (profile.generated_system_prompt) {
        parts.push(profile.generated_system_prompt)
        parts.push('')
    }

    // Reinforce master rules explicitly so the model treats them as hard constraints
    if (profile.generated_master_rules) {
        const { always_do, never_do, decision_criteria } = profile.generated_master_rules

        if (always_do?.length) {
            parts.push('### Reglas que debes respetar siempre')
            always_do.forEach(rule => parts.push(`- ${rule}`))
            parts.push('')
        }

        if (never_do?.length) {
            parts.push('### Cosas que debes evitar siempre')
            never_do.forEach(rule => parts.push(`- ${rule}`))
            parts.push('')
        }

        if (decision_criteria?.length) {
            parts.push('### Criterios de decisión del coach')
            decision_criteria.forEach(c => parts.push(`- ${c}`))
            parts.push('')
        }
    }

    parts.push('---')
    parts.push('')

    return parts.join('\n')
}

/**
 * Fallback used when no approved coach profile exists.
 * Neutral and professional — doesn't bias the AI in any direction.
 */
const FALLBACK_CONTEXT = `## Perfil del coach
Actúa como un asistente experto en entrenamiento y nutrición. Aplica criterios profesionales basados en evidencia científica. Sé preciso, útil y concreto.

---

`
